#include <stddef.h>
#include <stdio.h>
#include "tic_tac_toe.h"

// 2^9 = 0x200 possible states for a player's pieces
#define NUM_STATES 0x200
// Using 64-bit words
#define HAS_WIN_WORD_SIZE 64
// How many 64-bit words to use
// Calculated using the ceiling division trick
#define HAS_WIN_LEN ((NUM_STATES + HAS_WIN_WORD_SIZE - 1) / HAS_WIN_WORD_SIZE)

static const ttt_bitboard win_conditions[] = {
	0x007, // 0b000000111
	0x038, // 0b000111000
	0x1c0, // 0b111000000
	0x049, // 0b001001001
	0x092, // 0b010010010
	0x124, // 0b100100100
	0x111, // 0b100010001
	0x054  // 0b001010100
};

static const size_t num_win_conditions =
        sizeof(win_conditions) / sizeof(win_conditions[0]);

int main(int argc, char* argv[]) {
	// Compress the 2^9 = 512 possible states for a player into a
	// contiguous bit-array
	// Using 8 × 64-bit ints to contains the 512 bits
	uint64_t has_win_bits[HAS_WIN_LEN] = { 0 };

	for (ttt_bitboard b = 0; b <= 0x1FF; b++)
		for (size_t w = 0; w < num_win_conditions; w++)
			if ((win_conditions[w] & b) == win_conditions[w])
				has_win_bits[b >> 6] |= 1ULL << (b & (64 - 1));

	printf("#ifndef TTT_HAS_WIN_BIT_ARRAY_H\n");
	printf("#define TTT_HAS_WIN_BIT_ARRAY_H\n\n");
	printf("#include <stdint.h>\n\n");
	printf("/**\n");
	printf(" * This file was generated by "
	       "`generate_has_win_bit_array.c`\n");
	printf(" */\n\n");
	printf("/**\n");
	printf(" * Compress the 2^9 = 512 possible states for a player into a "
	       "contiguous bit-\n");
	printf(" * array\n");
	printf(" * Using 8 × 64-bit ints to contains the 512 bits\n");
	printf(" *\n");
	printf(" * To determine if a bitboard has a win:\n");
	printf(" *\t1. Determine which 64-bit word the bitboard resides in:\n");
	printf(" *\t\thas_in_bits[bitboard >> 6]\n");
	printf(" *\t\t(This is an floor division by 64)\n");
	printf(" *\t2. Determine which bit in the 64-bit word the bitboard "
	       "corresponds to:\n");
	printf(" *\t\tbitboard & 63\n");
	printf(" *\t3. Shift the bit to the first position:\n");
	printf(" *\t\thas_win_bits[b >> 6] >> (b & 63)\n");
	printf(" *\t4. Mask out the other bits except the first:\n");
	printf(" *\t\t(has_win_bits[b >> 6] >> (b & 63)) & 1\n");
	printf(" */\n");
	printf("static const uint64_t has_win_bits[] = {\n");
	for (size_t i = 0; i < HAS_WIN_LEN; i++)
		printf("\t0x%016llxULL%s\n",
		       (unsigned long long)has_win_bits[i],
		       i < HAS_WIN_LEN - 1 ? "," : "");
	printf("};\n\n");
	printf("#endif\n");

	return 0;
}
