#include <stddef.h>
#include <stdio.h>
#include <inttypes.h>
#include "tic_tac_toe.h"
#include "prng.h"

int main(int argc, char* argv[]) {
	uint64_t seed = 0xC0010FFF0CACC1AULL;
	uint64_t s[4];

	for (int i = 0; i < 4; i++)
		s[i] = splitmix64(&seed);

	printf("/**\n");
	printf(" * This file was generated by "
	       "`generate_ttt_zobrist_hashes.c`\n");
	printf(" */\n\n");

	printf("#ifndef TTT_ZOBRIST_HASHES_H\n");
	printf("#define TTT_ZOBRIST_HASHES_H\n\n");

	printf("#include <stdint.h>\n\n");

	printf("// These random numbers were created from the generators in "
	       "`prng.c`\n");
	printf("static const uint64_t zobrist_turn[%d] = {\n", TTT_NUM_PLAYERS);
	for (size_t p = 0; p < TTT_NUM_PLAYERS; p++) {
		printf("\tUINT64_C(0x%016" PRIX64 ")", xoshiro256ss(s));

		if (p < TTT_NUM_PLAYERS - 1)
			printf(",");

		printf("\n");
	}
	printf("};\n\n");

	printf("static const uint64_t zobrist_board[%d][%d] = {\n",
	       TTT_NUM_PLAYERS, TTT_BOARD_SIZE);
	for (size_t p = 0; p < TTT_NUM_PLAYERS; p++) {
		printf("\t/* Player %zu */\n\t{", p + 1);
		for (size_t sq = 0; sq < TTT_BOARD_SIZE; sq++) {
			if (sq % TTT_NUM_COLS == 0)
				printf("\n\t\t");

			printf("UINT64_C(0x%016" PRIX64 ")", xoshiro256ss(s));

			if (sq < TTT_BOARD_SIZE - 1)
				printf(",");
			if ((sq + 1) % TTT_NUM_COLS != 0)
				printf(" ");
		}

		printf("\n\t}");
		if (p < TTT_NUM_PLAYERS - 1)
			printf(",");
		printf("\n");
	}
	printf("};\n\n");

	printf("#endif\n");

	return 0;
}
