#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <inttypes.h>
#include "games/tic_tac_toe.h"

// 2^9 = 0x200 possible states for a player's pieces
#define NUM_STATES 0x200
// Using 64-bit words
#define HAS_WIN_WORD_SIZE 64
// How many 64-bit words to use
// Calculated using the ceiling division trick
#define HAS_WIN_LEN ((NUM_STATES + HAS_WIN_WORD_SIZE - 1) / HAS_WIN_WORD_SIZE)

static const ttt_bitboard win_conditions[] = {
	0x007, // 0b000000111
	0x038, // 0b000111000
	0x1c0, // 0b111000000
	0x049, // 0b001001001
	0x092, // 0b010010010
	0x124, // 0b100100100
	0x111, // 0b100010001
	0x054  // 0b001010100
};

static const size_t num_win_conditions =
        sizeof(win_conditions) / sizeof(win_conditions[0]);

int main(int argc, char* argv[]) {
	// Compress the 2^9 = 512 possible states for a player into a
	// contiguous bit-array
	// Using 8 × 64-bit ints to contains the 512 bits
	uint64_t has_win_bits[HAS_WIN_LEN] = { 0 };

	for (ttt_bitboard b = 0; b < NUM_STATES; b++) {
		for (size_t w = 0; w < num_win_conditions; w++) {
			if ((b & win_conditions[w]) == win_conditions[w]) {
				has_win_bits[b / HAS_WIN_WORD_SIZE] |=
				        UINT64_C(1) << (b % HAS_WIN_WORD_SIZE);

				// If we already hit a win condition, don't
				// bother looping through the others
				break;
			}
		}
	}

	fputs("/**\n"
	      " * This file was generated by `generate_ttt_has_win_bit_array.c`\n"
	      " */\n\n"
	      "#ifndef TTT_HAS_WIN_BIT_ARRAY_H\n"
	      "#define TTT_HAS_WIN_BIT_ARRAY_H\n\n"
	      "#include <stdint.h>\n"
	      "#include <stdbool.h>\n"
	      "#include \"games/tic_tac_toe.h\"\n\n",
	      stdout);

	printf("static const uint64_t has_win_bits[%u] = {\n", HAS_WIN_LEN);
	for (size_t i = 0; i < HAS_WIN_LEN; ++i) {
		printf("\tUINT64_C(0x%016" PRIx64 ")%s\n", has_win_bits[i],
		       i + 1u < HAS_WIN_LEN ? "," : "");
	}

	fputs("};\n\n"
	      "static inline bool ttt_check_win(ttt_bitboard b) {\n"
	      "\t/**\n"
	      "\t * Slight optimisation, for *unsigned* integers:\n"
	      "\t *\tb >> 6 == b / 64\n"
	      "\t *\tb & 63 == b % 64\n"
	      "\t */\n"
	      "\treturn (has_win_bits[b >> 6] >> (b & 63)) & 1;\n"
	      "}\n\n"
	      "#endif /* TTT_HAS_WIN_BIT_ARRAY_H */\n",
	      stdout);

	if (fflush(stdout) == EOF || ferror(stdout)) {
		fputs("Failed to write generated header ttt_has_win_bit_array.h\n", stderr);
		return 1;
	}
	return 0;
}
